drop table if exists comments;
drop table if exists book_genre_links;
drop table if exists books;
drop table if exists authors;
drop table if exists genres;


create table authors(id bigint generated by default as identity primary key, name varchar(255) unique not null);

create table genres(id bigint generated by default as identity primary key, name varchar(255) unique not null);

create table books(id bigint generated by default as identity primary key, name varchar(255) not null, author_id bigint not null);
alter table books add foreign key (author_id) references authors (id);
create unique index on books (name, author_id);

create table book_genre_links(book_id bigint not null, genre_id bigint not null);
create unique index on book_genre_links (book_id, genre_id);
alter table book_genre_links add foreign key (book_id) references books (id);
alter table book_genre_links add foreign key (genre_id) references genres (id);
